// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/automation.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskRegistryService_RegisterTaskType_FullMethodName = "/automation.TaskRegistryService/RegisterTaskType"
	TaskRegistryService_GetTaskType_FullMethodName      = "/automation.TaskRegistryService/GetTaskType"
	TaskRegistryService_ListTaskTypes_FullMethodName    = "/automation.TaskRegistryService/ListTaskTypes"
)

// TaskRegistryServiceClient is the client API for TaskRegistryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for task type registration
type TaskRegistryServiceClient interface {
	RegisterTaskType(ctx context.Context, in *RegisterTaskTypeRequest, opts ...grpc.CallOption) (*RegisterTaskTypeResponse, error)
	GetTaskType(ctx context.Context, in *GetTaskTypeRequest, opts ...grpc.CallOption) (*GetTaskTypeResponse, error)
	ListTaskTypes(ctx context.Context, in *ListTaskTypesRequest, opts ...grpc.CallOption) (*ListTaskTypesResponse, error)
}

type taskRegistryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskRegistryServiceClient(cc grpc.ClientConnInterface) TaskRegistryServiceClient {
	return &taskRegistryServiceClient{cc}
}

func (c *taskRegistryServiceClient) RegisterTaskType(ctx context.Context, in *RegisterTaskTypeRequest, opts ...grpc.CallOption) (*RegisterTaskTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTaskTypeResponse)
	err := c.cc.Invoke(ctx, TaskRegistryService_RegisterTaskType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRegistryServiceClient) GetTaskType(ctx context.Context, in *GetTaskTypeRequest, opts ...grpc.CallOption) (*GetTaskTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskTypeResponse)
	err := c.cc.Invoke(ctx, TaskRegistryService_GetTaskType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRegistryServiceClient) ListTaskTypes(ctx context.Context, in *ListTaskTypesRequest, opts ...grpc.CallOption) (*ListTaskTypesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTaskTypesResponse)
	err := c.cc.Invoke(ctx, TaskRegistryService_ListTaskTypes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskRegistryServiceServer is the server API for TaskRegistryService service.
// All implementations must embed UnimplementedTaskRegistryServiceServer
// for forward compatibility.
//
// Service for task type registration
type TaskRegistryServiceServer interface {
	RegisterTaskType(context.Context, *RegisterTaskTypeRequest) (*RegisterTaskTypeResponse, error)
	GetTaskType(context.Context, *GetTaskTypeRequest) (*GetTaskTypeResponse, error)
	ListTaskTypes(context.Context, *ListTaskTypesRequest) (*ListTaskTypesResponse, error)
	mustEmbedUnimplementedTaskRegistryServiceServer()
}

// UnimplementedTaskRegistryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskRegistryServiceServer struct{}

func (UnimplementedTaskRegistryServiceServer) RegisterTaskType(context.Context, *RegisterTaskTypeRequest) (*RegisterTaskTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTaskType not implemented")
}
func (UnimplementedTaskRegistryServiceServer) GetTaskType(context.Context, *GetTaskTypeRequest) (*GetTaskTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskType not implemented")
}
func (UnimplementedTaskRegistryServiceServer) ListTaskTypes(context.Context, *ListTaskTypesRequest) (*ListTaskTypesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTaskTypes not implemented")
}
func (UnimplementedTaskRegistryServiceServer) mustEmbedUnimplementedTaskRegistryServiceServer() {}
func (UnimplementedTaskRegistryServiceServer) testEmbeddedByValue()                             {}

// UnsafeTaskRegistryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskRegistryServiceServer will
// result in compilation errors.
type UnsafeTaskRegistryServiceServer interface {
	mustEmbedUnimplementedTaskRegistryServiceServer()
}

func RegisterTaskRegistryServiceServer(s grpc.ServiceRegistrar, srv TaskRegistryServiceServer) {
	// If the following call pancis, it indicates UnimplementedTaskRegistryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskRegistryService_ServiceDesc, srv)
}

func _TaskRegistryService_RegisterTaskType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTaskTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRegistryServiceServer).RegisterTaskType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRegistryService_RegisterTaskType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRegistryServiceServer).RegisterTaskType(ctx, req.(*RegisterTaskTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRegistryService_GetTaskType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRegistryServiceServer).GetTaskType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRegistryService_GetTaskType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRegistryServiceServer).GetTaskType(ctx, req.(*GetTaskTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRegistryService_ListTaskTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTaskTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRegistryServiceServer).ListTaskTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRegistryService_ListTaskTypes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRegistryServiceServer).ListTaskTypes(ctx, req.(*ListTaskTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskRegistryService_ServiceDesc is the grpc.ServiceDesc for TaskRegistryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskRegistryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "automation.TaskRegistryService",
	HandlerType: (*TaskRegistryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterTaskType",
			Handler:    _TaskRegistryService_RegisterTaskType_Handler,
		},
		{
			MethodName: "GetTaskType",
			Handler:    _TaskRegistryService_GetTaskType_Handler,
		},
		{
			MethodName: "ListTaskTypes",
			Handler:    _TaskRegistryService_ListTaskTypes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/automation.proto",
}

const (
	WorkerService_RegisterWorker_FullMethodName    = "/automation.WorkerService/RegisterWorker"
	WorkerService_UnregisterWorker_FullMethodName  = "/automation.WorkerService/UnregisterWorker"
	WorkerService_PollTask_FullMethodName          = "/automation.WorkerService/PollTask"
	WorkerService_CompleteTask_FullMethodName      = "/automation.WorkerService/CompleteTask"
	WorkerService_StartLiveWorkflow_FullMethodName = "/automation.WorkerService/StartLiveWorkflow"
	WorkerService_ExecuteTasks_FullMethodName      = "/automation.WorkerService/ExecuteTasks"
	WorkerService_GetTaskResults_FullMethodName    = "/automation.WorkerService/GetTaskResults"
	WorkerService_CompleteWorkflow_FullMethodName  = "/automation.WorkerService/CompleteWorkflow"
	WorkerService_SubscribeFailures_FullMethodName = "/automation.WorkerService/SubscribeFailures"
)

// WorkerServiceClient is the client API for WorkerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for worker registration and task polling - external SDKs call this
type WorkerServiceClient interface {
	RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error)
	UnregisterWorker(ctx context.Context, in *UnregisterWorkerRequest, opts ...grpc.CallOption) (*UnregisterWorkerResponse, error)
	PollTask(ctx context.Context, in *PollTaskRequest, opts ...grpc.CallOption) (*TaskRequest, error)
	CompleteTask(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*CompleteTaskResponse, error)
	StartLiveWorkflow(ctx context.Context, in *StartLiveWorkflowRequest, opts ...grpc.CallOption) (*StartLiveWorkflowResponse, error)
	ExecuteTasks(ctx context.Context, in *ExecuteTasksRequest, opts ...grpc.CallOption) (*ExecuteTasksResponse, error)
	GetTaskResults(ctx context.Context, in *GetTaskResultsRequest, opts ...grpc.CallOption) (*GetTaskResultsResponse, error)
	CompleteWorkflow(ctx context.Context, in *CompleteWorkflowRequest, opts ...grpc.CallOption) (*CompleteWorkflowResponse, error)
	// Failure notifications - streaming connection for receiving fatal workflow failures
	SubscribeFailures(ctx context.Context, in *SubscribeFailuresRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowFailureNotification], error)
}

type workerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerServiceClient(cc grpc.ClientConnInterface) WorkerServiceClient {
	return &workerServiceClient{cc}
}

func (c *workerServiceClient) RegisterWorker(ctx context.Context, in *RegisterWorkerRequest, opts ...grpc.CallOption) (*RegisterWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWorkerResponse)
	err := c.cc.Invoke(ctx, WorkerService_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) UnregisterWorker(ctx context.Context, in *UnregisterWorkerRequest, opts ...grpc.CallOption) (*UnregisterWorkerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterWorkerResponse)
	err := c.cc.Invoke(ctx, WorkerService_UnregisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) PollTask(ctx context.Context, in *PollTaskRequest, opts ...grpc.CallOption) (*TaskRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskRequest)
	err := c.cc.Invoke(ctx, WorkerService_PollTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CompleteTask(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*CompleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteTaskResponse)
	err := c.cc.Invoke(ctx, WorkerService_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) StartLiveWorkflow(ctx context.Context, in *StartLiveWorkflowRequest, opts ...grpc.CallOption) (*StartLiveWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartLiveWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkerService_StartLiveWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) ExecuteTasks(ctx context.Context, in *ExecuteTasksRequest, opts ...grpc.CallOption) (*ExecuteTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteTasksResponse)
	err := c.cc.Invoke(ctx, WorkerService_ExecuteTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) GetTaskResults(ctx context.Context, in *GetTaskResultsRequest, opts ...grpc.CallOption) (*GetTaskResultsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResultsResponse)
	err := c.cc.Invoke(ctx, WorkerService_GetTaskResults_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) CompleteWorkflow(ctx context.Context, in *CompleteWorkflowRequest, opts ...grpc.CallOption) (*CompleteWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteWorkflowResponse)
	err := c.cc.Invoke(ctx, WorkerService_CompleteWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workerServiceClient) SubscribeFailures(ctx context.Context, in *SubscribeFailuresRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkflowFailureNotification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WorkerService_ServiceDesc.Streams[0], WorkerService_SubscribeFailures_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeFailuresRequest, WorkflowFailureNotification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_SubscribeFailuresClient = grpc.ServerStreamingClient[WorkflowFailureNotification]

// WorkerServiceServer is the server API for WorkerService service.
// All implementations must embed UnimplementedWorkerServiceServer
// for forward compatibility.
//
// Service for worker registration and task polling - external SDKs call this
type WorkerServiceServer interface {
	RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error)
	UnregisterWorker(context.Context, *UnregisterWorkerRequest) (*UnregisterWorkerResponse, error)
	PollTask(context.Context, *PollTaskRequest) (*TaskRequest, error)
	CompleteTask(context.Context, *TaskResult) (*CompleteTaskResponse, error)
	StartLiveWorkflow(context.Context, *StartLiveWorkflowRequest) (*StartLiveWorkflowResponse, error)
	ExecuteTasks(context.Context, *ExecuteTasksRequest) (*ExecuteTasksResponse, error)
	GetTaskResults(context.Context, *GetTaskResultsRequest) (*GetTaskResultsResponse, error)
	CompleteWorkflow(context.Context, *CompleteWorkflowRequest) (*CompleteWorkflowResponse, error)
	// Failure notifications - streaming connection for receiving fatal workflow failures
	SubscribeFailures(*SubscribeFailuresRequest, grpc.ServerStreamingServer[WorkflowFailureNotification]) error
	mustEmbedUnimplementedWorkerServiceServer()
}

// UnimplementedWorkerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerServiceServer struct{}

func (UnimplementedWorkerServiceServer) RegisterWorker(context.Context, *RegisterWorkerRequest) (*RegisterWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedWorkerServiceServer) UnregisterWorker(context.Context, *UnregisterWorkerRequest) (*UnregisterWorkerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterWorker not implemented")
}
func (UnimplementedWorkerServiceServer) PollTask(context.Context, *PollTaskRequest) (*TaskRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PollTask not implemented")
}
func (UnimplementedWorkerServiceServer) CompleteTask(context.Context, *TaskResult) (*CompleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedWorkerServiceServer) StartLiveWorkflow(context.Context, *StartLiveWorkflowRequest) (*StartLiveWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLiveWorkflow not implemented")
}
func (UnimplementedWorkerServiceServer) ExecuteTasks(context.Context, *ExecuteTasksRequest) (*ExecuteTasksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTasks not implemented")
}
func (UnimplementedWorkerServiceServer) GetTaskResults(context.Context, *GetTaskResultsRequest) (*GetTaskResultsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskResults not implemented")
}
func (UnimplementedWorkerServiceServer) CompleteWorkflow(context.Context, *CompleteWorkflowRequest) (*CompleteWorkflowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteWorkflow not implemented")
}
func (UnimplementedWorkerServiceServer) SubscribeFailures(*SubscribeFailuresRequest, grpc.ServerStreamingServer[WorkflowFailureNotification]) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeFailures not implemented")
}
func (UnimplementedWorkerServiceServer) mustEmbedUnimplementedWorkerServiceServer() {}
func (UnimplementedWorkerServiceServer) testEmbeddedByValue()                       {}

// UnsafeWorkerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerServiceServer will
// result in compilation errors.
type UnsafeWorkerServiceServer interface {
	mustEmbedUnimplementedWorkerServiceServer()
}

func RegisterWorkerServiceServer(s grpc.ServiceRegistrar, srv WorkerServiceServer) {
	// If the following call pancis, it indicates UnimplementedWorkerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerService_ServiceDesc, srv)
}

func _WorkerService_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).RegisterWorker(ctx, req.(*RegisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_UnregisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterWorkerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).UnregisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_UnregisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).UnregisterWorker(ctx, req.(*UnregisterWorkerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_PollTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).PollTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_PollTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).PollTask(ctx, req.(*PollTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CompleteTask(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_StartLiveWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLiveWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).StartLiveWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_StartLiveWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).StartLiveWorkflow(ctx, req.(*StartLiveWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_ExecuteTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).ExecuteTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_ExecuteTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).ExecuteTasks(ctx, req.(*ExecuteTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_GetTaskResults_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskResultsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).GetTaskResults(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_GetTaskResults_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).GetTaskResults(ctx, req.(*GetTaskResultsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_CompleteWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerServiceServer).CompleteWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerService_CompleteWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerServiceServer).CompleteWorkflow(ctx, req.(*CompleteWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkerService_SubscribeFailures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeFailuresRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WorkerServiceServer).SubscribeFailures(m, &grpc.GenericServerStream[SubscribeFailuresRequest, WorkflowFailureNotification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WorkerService_SubscribeFailuresServer = grpc.ServerStreamingServer[WorkflowFailureNotification]

// WorkerService_ServiceDesc is the grpc.ServiceDesc for WorkerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "automation.WorkerService",
	HandlerType: (*WorkerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _WorkerService_RegisterWorker_Handler,
		},
		{
			MethodName: "UnregisterWorker",
			Handler:    _WorkerService_UnregisterWorker_Handler,
		},
		{
			MethodName: "PollTask",
			Handler:    _WorkerService_PollTask_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _WorkerService_CompleteTask_Handler,
		},
		{
			MethodName: "StartLiveWorkflow",
			Handler:    _WorkerService_StartLiveWorkflow_Handler,
		},
		{
			MethodName: "ExecuteTasks",
			Handler:    _WorkerService_ExecuteTasks_Handler,
		},
		{
			MethodName: "GetTaskResults",
			Handler:    _WorkerService_GetTaskResults_Handler,
		},
		{
			MethodName: "CompleteWorkflow",
			Handler:    _WorkerService_CompleteWorkflow_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeFailures",
			Handler:       _WorkerService_SubscribeFailures_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/automation.proto",
}
