// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v5.29.3
// source: proto/automation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FailureType int32

const (
	FailureType_FAILURE_TYPE_UNKNOWN                FailureType = 0
	FailureType_FAILURE_TYPE_TASK_EXHAUSTED_RETRIES FailureType = 1
	FailureType_FAILURE_TYPE_ROUTER_UNAVAILABLE     FailureType = 2
	FailureType_FAILURE_TYPE_LEADER_UNAVAILABLE     FailureType = 3
	FailureType_FAILURE_TYPE_SYSTEM_ERROR           FailureType = 4
)

// Enum value maps for FailureType.
var (
	FailureType_name = map[int32]string{
		0: "FAILURE_TYPE_UNKNOWN",
		1: "FAILURE_TYPE_TASK_EXHAUSTED_RETRIES",
		2: "FAILURE_TYPE_ROUTER_UNAVAILABLE",
		3: "FAILURE_TYPE_LEADER_UNAVAILABLE",
		4: "FAILURE_TYPE_SYSTEM_ERROR",
	}
	FailureType_value = map[string]int32{
		"FAILURE_TYPE_UNKNOWN":                0,
		"FAILURE_TYPE_TASK_EXHAUSTED_RETRIES": 1,
		"FAILURE_TYPE_ROUTER_UNAVAILABLE":     2,
		"FAILURE_TYPE_LEADER_UNAVAILABLE":     3,
		"FAILURE_TYPE_SYSTEM_ERROR":           4,
	}
)

func (x FailureType) Enum() *FailureType {
	p := new(FailureType)
	*p = x
	return p
}

func (x FailureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_automation_proto_enumTypes[0].Descriptor()
}

func (FailureType) Type() protoreflect.EnumType {
	return &file_proto_automation_proto_enumTypes[0]
}

func (x FailureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureType.Descriptor instead.
func (FailureType) EnumDescriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{0}
}

// Worker registration messages
type RegisterWorkerRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TaskTypes          []string               `protobuf:"bytes,1,rep,name=task_types,json=taskTypes,proto3" json:"task_types,omitempty"`
	MaxConcurrentTasks int32                  `protobuf:"varint,2,opt,name=max_concurrent_tasks,json=maxConcurrentTasks,proto3" json:"max_concurrent_tasks,omitempty"`
	Metadata           map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_automation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterWorkerRequest) GetTaskTypes() []string {
	if x != nil {
		return x.TaskTypes
	}
	return nil
}

func (x *RegisterWorkerRequest) GetMaxConcurrentTasks() int32 {
	if x != nil {
		return x.MaxConcurrentTasks
	}
	return 0
}

func (x *RegisterWorkerRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PollTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TaskTypes     []string               `protobuf:"bytes,2,rep,name=task_types,json=taskTypes,proto3" json:"task_types,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollTaskRequest) Reset() {
	*x = PollTaskRequest{}
	mi := &file_proto_automation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollTaskRequest) ProtoMessage() {}

func (x *PollTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollTaskRequest.ProtoReflect.Descriptor instead.
func (*PollTaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{1}
}

func (x *PollTaskRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *PollTaskRequest) GetTaskTypes() []string {
	if x != nil {
		return x.TaskTypes
	}
	return nil
}

func (x *PollTaskRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

// Response for task completion
type CompleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskResponse) Reset() {
	*x = CompleteTaskResponse{}
	mi := &file_proto_automation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskResponse) ProtoMessage() {}

func (x *CompleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{2}
}

func (x *CompleteTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterWorkerResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NodeId           int64                  `protobuf:"varint,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	RedirectRequired bool                   `protobuf:"varint,4,opt,name=redirect_required,json=redirectRequired,proto3" json:"redirect_required,omitempty"`
	RouterEndpoints  []string               `protobuf:"bytes,5,rep,name=router_endpoints,json=routerEndpoints,proto3" json:"router_endpoints,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_proto_automation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterWorkerResponse) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *RegisterWorkerResponse) GetRedirectRequired() bool {
	if x != nil {
		return x.RedirectRequired
	}
	return false
}

func (x *RegisterWorkerResponse) GetRouterEndpoints() []string {
	if x != nil {
		return x.RouterEndpoints
	}
	return nil
}

type UnregisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterWorkerRequest) Reset() {
	*x = UnregisterWorkerRequest{}
	mi := &file_proto_automation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterWorkerRequest) ProtoMessage() {}

func (x *UnregisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*UnregisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{4}
}

func (x *UnregisterWorkerRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type UnregisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterWorkerResponse) Reset() {
	*x = UnregisterWorkerResponse{}
	mi := &file_proto_automation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterWorkerResponse) ProtoMessage() {}

func (x *UnregisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*UnregisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{5}
}

func (x *UnregisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Task type definition
type TaskTypeSchema struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	InputSchema      []byte                 `protobuf:"bytes,3,opt,name=input_schema,json=inputSchema,proto3" json:"input_schema,omitempty"`
	OutputSchema     []byte                 `protobuf:"bytes,4,opt,name=output_schema,json=outputSchema,proto3" json:"output_schema,omitempty"`
	DefaultTimeoutMs int32                  `protobuf:"varint,5,opt,name=default_timeout_ms,json=defaultTimeoutMs,proto3" json:"default_timeout_ms,omitempty"`
	Category         string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Handler          string                 `protobuf:"bytes,7,opt,name=handler,proto3" json:"handler,omitempty"`
	Icon             string                 `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	Color            string                 `protobuf:"bytes,9,opt,name=color,proto3" json:"color,omitempty"`
	IsActive         bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskTypeSchema) Reset() {
	*x = TaskTypeSchema{}
	mi := &file_proto_automation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskTypeSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskTypeSchema) ProtoMessage() {}

func (x *TaskTypeSchema) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskTypeSchema.ProtoReflect.Descriptor instead.
func (*TaskTypeSchema) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{6}
}

func (x *TaskTypeSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TaskTypeSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *TaskTypeSchema) GetInputSchema() []byte {
	if x != nil {
		return x.InputSchema
	}
	return nil
}

func (x *TaskTypeSchema) GetOutputSchema() []byte {
	if x != nil {
		return x.OutputSchema
	}
	return nil
}

func (x *TaskTypeSchema) GetDefaultTimeoutMs() int32 {
	if x != nil {
		return x.DefaultTimeoutMs
	}
	return 0
}

func (x *TaskTypeSchema) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *TaskTypeSchema) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *TaskTypeSchema) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *TaskTypeSchema) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *TaskTypeSchema) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type RegisterTaskTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      *TaskTypeSchema        `protobuf:"bytes,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTaskTypeRequest) Reset() {
	*x = RegisterTaskTypeRequest{}
	mi := &file_proto_automation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTaskTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskTypeRequest) ProtoMessage() {}

func (x *RegisterTaskTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskTypeRequest.ProtoReflect.Descriptor instead.
func (*RegisterTaskTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterTaskTypeRequest) GetTaskType() *TaskTypeSchema {
	if x != nil {
		return x.TaskType
	}
	return nil
}

type RegisterTaskTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TaskTypeId    int64                  `protobuf:"varint,3,opt,name=task_type_id,json=taskTypeId,proto3" json:"task_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTaskTypeResponse) Reset() {
	*x = RegisterTaskTypeResponse{}
	mi := &file_proto_automation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTaskTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTaskTypeResponse) ProtoMessage() {}

func (x *RegisterTaskTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTaskTypeResponse.ProtoReflect.Descriptor instead.
func (*RegisterTaskTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterTaskTypeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterTaskTypeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterTaskTypeResponse) GetTaskTypeId() int64 {
	if x != nil {
		return x.TaskTypeId
	}
	return 0
}

type GetTaskTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskTypeRequest) Reset() {
	*x = GetTaskTypeRequest{}
	mi := &file_proto_automation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskTypeRequest) ProtoMessage() {}

func (x *GetTaskTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskTypeRequest.ProtoReflect.Descriptor instead.
func (*GetTaskTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{9}
}

func (x *GetTaskTypeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTaskTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	TaskType      *TaskTypeSchema        `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskTypeResponse) Reset() {
	*x = GetTaskTypeResponse{}
	mi := &file_proto_automation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskTypeResponse) ProtoMessage() {}

func (x *GetTaskTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskTypeResponse.ProtoReflect.Descriptor instead.
func (*GetTaskTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{10}
}

func (x *GetTaskTypeResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetTaskTypeResponse) GetTaskType() *TaskTypeSchema {
	if x != nil {
		return x.TaskType
	}
	return nil
}

type ListTaskTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskTypesRequest) Reset() {
	*x = ListTaskTypesRequest{}
	mi := &file_proto_automation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskTypesRequest) ProtoMessage() {}

func (x *ListTaskTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskTypesRequest.ProtoReflect.Descriptor instead.
func (*ListTaskTypesRequest) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{11}
}

func (x *ListTaskTypesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListTaskTypesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ListTaskTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskTypes     []*TaskTypeSchema      `protobuf:"bytes,1,rep,name=task_types,json=taskTypes,proto3" json:"task_types,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskTypesResponse) Reset() {
	*x = ListTaskTypesResponse{}
	mi := &file_proto_automation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskTypesResponse) ProtoMessage() {}

func (x *ListTaskTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskTypesResponse.ProtoReflect.Descriptor instead.
func (*ListTaskTypesResponse) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{12}
}

func (x *ListTaskTypesResponse) GetTaskTypes() []*TaskTypeSchema {
	if x != nil {
		return x.TaskTypes
	}
	return nil
}

func (x *ListTaskTypesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type TaskRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType          string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Input             []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	WorkflowId        int64                  `protobuf:"varint,4,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	StageIndex        int32                  `protobuf:"varint,5,opt,name=stage_index,json=stageIndex,proto3" json:"stage_index,omitempty"`
	TimeoutMs         int32                  `protobuf:"varint,6,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Metadata          map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PublisherRouterId int64                  `protobuf:"varint,8,opt,name=publisher_router_id,json=publisherRouterId,proto3" json:"publisher_router_id,omitempty"`
	PublisherWorkerId int64                  `protobuf:"varint,9,opt,name=publisher_worker_id,json=publisherWorkerId,proto3" json:"publisher_worker_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_proto_automation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{13}
}

func (x *TaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TaskRequest) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *TaskRequest) GetStageIndex() int32 {
	if x != nil {
		return x.StageIndex
	}
	return 0
}

func (x *TaskRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *TaskRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *TaskRequest) GetPublisherRouterId() int64 {
	if x != nil {
		return x.PublisherRouterId
	}
	return 0
}

func (x *TaskRequest) GetPublisherWorkerId() int64 {
	if x != nil {
		return x.PublisherWorkerId
	}
	return 0
}

type TaskResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TaskId            int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success           bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Output            []byte                 `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	Error             string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	ExecutionTimeMs   int64                  `protobuf:"varint,5,opt,name=execution_time_ms,json=executionTimeMs,proto3" json:"execution_time_ms,omitempty"`
	WorkflowId        int64                  `protobuf:"varint,6,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	PublisherRouterId int64                  `protobuf:"varint,7,opt,name=publisher_router_id,json=publisherRouterId,proto3" json:"publisher_router_id,omitempty"`
	PublisherWorkerId int64                  `protobuf:"varint,8,opt,name=publisher_worker_id,json=publisherWorkerId,proto3" json:"publisher_worker_id,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_automation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{14}
}

func (x *TaskResult) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResult) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *TaskResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *TaskResult) GetExecutionTimeMs() int64 {
	if x != nil {
		return x.ExecutionTimeMs
	}
	return 0
}

func (x *TaskResult) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *TaskResult) GetPublisherRouterId() int64 {
	if x != nil {
		return x.PublisherRouterId
	}
	return 0
}

func (x *TaskResult) GetPublisherWorkerId() int64 {
	if x != nil {
		return x.PublisherWorkerId
	}
	return 0
}

type TaskSubmit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      string                 `protobuf:"bytes,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Input         []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	StageIndex    int32                  `protobuf:"varint,4,opt,name=stage_index,json=stageIndex,proto3" json:"stage_index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSubmit) Reset() {
	*x = TaskSubmit{}
	mi := &file_proto_automation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSubmit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSubmit) ProtoMessage() {}

func (x *TaskSubmit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSubmit.ProtoReflect.Descriptor instead.
func (*TaskSubmit) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{15}
}

func (x *TaskSubmit) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *TaskSubmit) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *TaskSubmit) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *TaskSubmit) GetStageIndex() int32 {
	if x != nil {
		return x.StageIndex
	}
	return 0
}

type TaskSubmitResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskSubmitResult) Reset() {
	*x = TaskSubmitResult{}
	mi := &file_proto_automation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskSubmitResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskSubmitResult) ProtoMessage() {}

func (x *TaskSubmitResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskSubmitResult.ProtoReflect.Descriptor instead.
func (*TaskSubmitResult) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{16}
}

func (x *TaskSubmitResult) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskSubmitResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskSubmitResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ExecuteTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    int64                  `protobuf:"varint,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	NodeId        int64                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Tasks         []*TaskSubmit          `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTasksRequest) Reset() {
	*x = ExecuteTasksRequest{}
	mi := &file_proto_automation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTasksRequest) ProtoMessage() {}

func (x *ExecuteTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTasksRequest.ProtoReflect.Descriptor instead.
func (*ExecuteTasksRequest) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{17}
}

func (x *ExecuteTasksRequest) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *ExecuteTasksRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *ExecuteTasksRequest) GetTasks() []*TaskSubmit {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type ExecuteTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TaskSubmitResult    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTasksResponse) Reset() {
	*x = ExecuteTasksResponse{}
	mi := &file_proto_automation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTasksResponse) ProtoMessage() {}

func (x *ExecuteTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTasksResponse.ProtoReflect.Descriptor instead.
func (*ExecuteTasksResponse) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{18}
}

func (x *ExecuteTasksResponse) GetResults() []*TaskSubmitResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type TaskResultQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultQuery) Reset() {
	*x = TaskResultQuery{}
	mi := &file_proto_automation_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultQuery) ProtoMessage() {}

func (x *TaskResultQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultQuery.ProtoReflect.Descriptor instead.
func (*TaskResultQuery) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{19}
}

func (x *TaskResultQuery) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

type TaskResultItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Success       bool                   `protobuf:"varint,3,opt,name=success,proto3" json:"success,omitempty"`
	Output        []byte                 `protobuf:"bytes,4,opt,name=output,proto3" json:"output,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResultItem) Reset() {
	*x = TaskResultItem{}
	mi := &file_proto_automation_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResultItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResultItem) ProtoMessage() {}

func (x *TaskResultItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResultItem.ProtoReflect.Descriptor instead.
func (*TaskResultItem) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{20}
}

func (x *TaskResultItem) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *TaskResultItem) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *TaskResultItem) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TaskResultItem) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *TaskResultItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetTaskResultsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    int64                  `protobuf:"varint,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,2,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	Tasks         []*TaskResultQuery     `protobuf:"bytes,3,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultsRequest) Reset() {
	*x = GetTaskResultsRequest{}
	mi := &file_proto_automation_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultsRequest) ProtoMessage() {}

func (x *GetTaskResultsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultsRequest.ProtoReflect.Descriptor instead.
func (*GetTaskResultsRequest) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{21}
}

func (x *GetTaskResultsRequest) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *GetTaskResultsRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

func (x *GetTaskResultsRequest) GetTasks() []*TaskResultQuery {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetTaskResultsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*TaskResultItem      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResultsResponse) Reset() {
	*x = GetTaskResultsResponse{}
	mi := &file_proto_automation_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResultsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResultsResponse) ProtoMessage() {}

func (x *GetTaskResultsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResultsResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResultsResponse) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{22}
}

func (x *GetTaskResultsResponse) GetResults() []*TaskResultItem {
	if x != nil {
		return x.Results
	}
	return nil
}

type StartLiveWorkflowRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	FailureCallback bool                   `protobuf:"varint,2,opt,name=failure_callback,json=failureCallback,proto3" json:"failure_callback,omitempty"`
	WorkflowName    string                 `protobuf:"bytes,3,opt,name=workflow_name,json=workflowName,proto3" json:"workflow_name,omitempty"`
	TimeoutMs       int32                  `protobuf:"varint,4,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StartLiveWorkflowRequest) Reset() {
	*x = StartLiveWorkflowRequest{}
	mi := &file_proto_automation_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLiveWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLiveWorkflowRequest) ProtoMessage() {}

func (x *StartLiveWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLiveWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartLiveWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{23}
}

func (x *StartLiveWorkflowRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *StartLiveWorkflowRequest) GetFailureCallback() bool {
	if x != nil {
		return x.FailureCallback
	}
	return false
}

func (x *StartLiveWorkflowRequest) GetWorkflowName() string {
	if x != nil {
		return x.WorkflowName
	}
	return ""
}

func (x *StartLiveWorkflowRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type StartLiveWorkflowResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	WorkflowId        int64                  `protobuf:"varint,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	PublisherRouterId int64                  `protobuf:"varint,3,opt,name=publisher_router_id,json=publisherRouterId,proto3" json:"publisher_router_id,omitempty"`
	Error             string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StartLiveWorkflowResponse) Reset() {
	*x = StartLiveWorkflowResponse{}
	mi := &file_proto_automation_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartLiveWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartLiveWorkflowResponse) ProtoMessage() {}

func (x *StartLiveWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartLiveWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartLiveWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{24}
}

func (x *StartLiveWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartLiveWorkflowResponse) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *StartLiveWorkflowResponse) GetPublisherRouterId() int64 {
	if x != nil {
		return x.PublisherRouterId
	}
	return 0
}

func (x *StartLiveWorkflowResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompleteWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    int64                  `protobuf:"varint,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteWorkflowRequest) Reset() {
	*x = CompleteWorkflowRequest{}
	mi := &file_proto_automation_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteWorkflowRequest) ProtoMessage() {}

func (x *CompleteWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CompleteWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{25}
}

func (x *CompleteWorkflowRequest) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *CompleteWorkflowRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CompleteWorkflowRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type CompleteWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteWorkflowResponse) Reset() {
	*x = CompleteWorkflowResponse{}
	mi := &file_proto_automation_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteWorkflowResponse) ProtoMessage() {}

func (x *CompleteWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CompleteWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{26}
}

func (x *CompleteWorkflowResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SubscribeFailuresRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int64                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeFailuresRequest) Reset() {
	*x = SubscribeFailuresRequest{}
	mi := &file_proto_automation_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeFailuresRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeFailuresRequest) ProtoMessage() {}

func (x *SubscribeFailuresRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeFailuresRequest.ProtoReflect.Descriptor instead.
func (*SubscribeFailuresRequest) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{27}
}

func (x *SubscribeFailuresRequest) GetNodeId() int64 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type WorkflowFailureNotification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    int64                  `protobuf:"varint,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	TaskId        int64                  `protobuf:"varint,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType      string                 `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	FailureType   FailureType            `protobuf:"varint,5,opt,name=failure_type,json=failureType,proto3,enum=automation.FailureType" json:"failure_type,omitempty"`
	RetryAttempts int32                  `protobuf:"varint,6,opt,name=retry_attempts,json=retryAttempts,proto3" json:"retry_attempts,omitempty"`
	Timestamp     int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowFailureNotification) Reset() {
	*x = WorkflowFailureNotification{}
	mi := &file_proto_automation_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowFailureNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowFailureNotification) ProtoMessage() {}

func (x *WorkflowFailureNotification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_automation_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowFailureNotification.ProtoReflect.Descriptor instead.
func (*WorkflowFailureNotification) Descriptor() ([]byte, []int) {
	return file_proto_automation_proto_rawDescGZIP(), []int{28}
}

func (x *WorkflowFailureNotification) GetWorkflowId() int64 {
	if x != nil {
		return x.WorkflowId
	}
	return 0
}

func (x *WorkflowFailureNotification) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *WorkflowFailureNotification) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *WorkflowFailureNotification) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WorkflowFailureNotification) GetFailureType() FailureType {
	if x != nil {
		return x.FailureType
	}
	return FailureType_FAILURE_TYPE_UNKNOWN
}

func (x *WorkflowFailureNotification) GetRetryAttempts() int32 {
	if x != nil {
		return x.RetryAttempts
	}
	return 0
}

func (x *WorkflowFailureNotification) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_proto_automation_proto protoreflect.FileDescriptor

const file_proto_automation_proto_rawDesc = "" +
	"\n" +
	"\x16proto/automation.proto\x12\n" +
	"automation\"\xf2\x01\n" +
	"\x15RegisterWorkerRequest\x12\x1d\n" +
	"\n" +
	"task_types\x18\x01 \x03(\tR\ttaskTypes\x120\n" +
	"\x14max_concurrent_tasks\x18\x02 \x01(\x05R\x12maxConcurrentTasks\x12K\n" +
	"\bmetadata\x18\x03 \x03(\v2/.automation.RegisterWorkerRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"h\n" +
	"\x0fPollTaskRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12\x1d\n" +
	"\n" +
	"task_types\x18\x02 \x03(\tR\ttaskTypes\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"J\n" +
	"\x14CompleteTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xbd\x01\n" +
	"\x16RegisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\x03R\x06nodeId\x12+\n" +
	"\x11redirect_required\x18\x04 \x01(\bR\x10redirectRequired\x12)\n" +
	"\x10router_endpoints\x18\x05 \x03(\tR\x0frouterEndpoints\"2\n" +
	"\x17UnregisterWorkerRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"4\n" +
	"\x18UnregisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb9\x02\n" +
	"\x0eTaskTypeSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\finput_schema\x18\x03 \x01(\fR\vinputSchema\x12#\n" +
	"\routput_schema\x18\x04 \x01(\fR\foutputSchema\x12,\n" +
	"\x12default_timeout_ms\x18\x05 \x01(\x05R\x10defaultTimeoutMs\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x18\n" +
	"\ahandler\x18\a \x01(\tR\ahandler\x12\x12\n" +
	"\x04icon\x18\b \x01(\tR\x04icon\x12\x14\n" +
	"\x05color\x18\t \x01(\tR\x05color\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\"R\n" +
	"\x17RegisterTaskTypeRequest\x127\n" +
	"\ttask_type\x18\x01 \x01(\v2\x1a.automation.TaskTypeSchemaR\btaskType\"p\n" +
	"\x18RegisterTaskTypeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\ftask_type_id\x18\x03 \x01(\x03R\n" +
	"taskTypeId\"(\n" +
	"\x12GetTaskTypeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"d\n" +
	"\x13GetTaskTypeResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x127\n" +
	"\ttask_type\x18\x02 \x01(\v2\x1a.automation.TaskTypeSchemaR\btaskType\"D\n" +
	"\x14ListTaskTypesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\"h\n" +
	"\x15ListTaskTypesResponse\x129\n" +
	"\n" +
	"task_types\x18\x01 \x03(\v2\x1a.automation.TaskTypeSchemaR\ttaskTypes\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x9a\x03\n" +
	"\vTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\x12\x1f\n" +
	"\vworkflow_id\x18\x04 \x01(\x03R\n" +
	"workflowId\x12\x1f\n" +
	"\vstage_index\x18\x05 \x01(\x05R\n" +
	"stageIndex\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x06 \x01(\x05R\ttimeoutMs\x12A\n" +
	"\bmetadata\x18\a \x03(\v2%.automation.TaskRequest.MetadataEntryR\bmetadata\x12.\n" +
	"\x13publisher_router_id\x18\b \x01(\x03R\x11publisherRouterId\x12.\n" +
	"\x13publisher_worker_id\x18\t \x01(\x03R\x11publisherWorkerId\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9a\x02\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x03 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12*\n" +
	"\x11execution_time_ms\x18\x05 \x01(\x03R\x0fexecutionTimeMs\x12\x1f\n" +
	"\vworkflow_id\x18\x06 \x01(\x03R\n" +
	"workflowId\x12.\n" +
	"\x13publisher_router_id\x18\a \x01(\x03R\x11publisherRouterId\x12.\n" +
	"\x13publisher_worker_id\x18\b \x01(\x03R\x11publisherWorkerId\"\x7f\n" +
	"\n" +
	"TaskSubmit\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\tR\btaskType\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\x12\x1f\n" +
	"\vstage_index\x18\x04 \x01(\x05R\n" +
	"stageIndex\"[\n" +
	"\x10TaskSubmitResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"}\n" +
	"\x13ExecuteTasksRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\x03R\n" +
	"workflowId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x03R\x06nodeId\x12,\n" +
	"\x05tasks\x18\x03 \x03(\v2\x16.automation.TaskSubmitR\x05tasks\"N\n" +
	"\x14ExecuteTasksResponse\x126\n" +
	"\aresults\x18\x01 \x03(\v2\x1c.automation.TaskSubmitResultR\aresults\"*\n" +
	"\x0fTaskResultQuery\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\"\x87\x01\n" +
	"\x0eTaskResultItem\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12\x18\n" +
	"\asuccess\x18\x03 \x01(\bR\asuccess\x12\x16\n" +
	"\x06output\x18\x04 \x01(\fR\x06output\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\x8a\x01\n" +
	"\x15GetTaskResultsRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\x03R\n" +
	"workflowId\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x02 \x01(\x05R\ttimeoutMs\x121\n" +
	"\x05tasks\x18\x03 \x03(\v2\x1b.automation.TaskResultQueryR\x05tasks\"N\n" +
	"\x16GetTaskResultsResponse\x124\n" +
	"\aresults\x18\x01 \x03(\v2\x1a.automation.TaskResultItemR\aresults\"\xa2\x01\n" +
	"\x18StartLiveWorkflowRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\x12)\n" +
	"\x10failure_callback\x18\x02 \x01(\bR\x0ffailureCallback\x12#\n" +
	"\rworkflow_name\x18\x03 \x01(\tR\fworkflowName\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x04 \x01(\x05R\ttimeoutMs\"\x9c\x01\n" +
	"\x19StartLiveWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\x03R\n" +
	"workflowId\x12.\n" +
	"\x13publisher_router_id\x18\x03 \x01(\x03R\x11publisherRouterId\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"j\n" +
	"\x17CompleteWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\x03R\n" +
	"workflowId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"4\n" +
	"\x18CompleteWorkflowResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x18SubscribeFailuresRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x03R\x06nodeId\"\x8b\x02\n" +
	"\x1bWorkflowFailureNotification\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\x03R\n" +
	"workflowId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\x03R\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12:\n" +
	"\ffailure_type\x18\x05 \x01(\x0e2\x17.automation.FailureTypeR\vfailureType\x12%\n" +
	"\x0eretry_attempts\x18\x06 \x01(\x05R\rretryAttempts\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp*\xb9\x01\n" +
	"\vFailureType\x12\x18\n" +
	"\x14FAILURE_TYPE_UNKNOWN\x10\x00\x12'\n" +
	"#FAILURE_TYPE_TASK_EXHAUSTED_RETRIES\x10\x01\x12#\n" +
	"\x1fFAILURE_TYPE_ROUTER_UNAVAILABLE\x10\x02\x12#\n" +
	"\x1fFAILURE_TYPE_LEADER_UNAVAILABLE\x10\x03\x12\x1d\n" +
	"\x19FAILURE_TYPE_SYSTEM_ERROR\x10\x042\x9a\x02\n" +
	"\x13TaskRegistryService\x12]\n" +
	"\x10RegisterTaskType\x12#.automation.RegisterTaskTypeRequest\x1a$.automation.RegisterTaskTypeResponse\x12N\n" +
	"\vGetTaskType\x12\x1e.automation.GetTaskTypeRequest\x1a\x1f.automation.GetTaskTypeResponse\x12T\n" +
	"\rListTaskTypes\x12 .automation.ListTaskTypesRequest\x1a!.automation.ListTaskTypesResponse2\xa6\x06\n" +
	"\rWorkerService\x12W\n" +
	"\x0eRegisterWorker\x12!.automation.RegisterWorkerRequest\x1a\".automation.RegisterWorkerResponse\x12]\n" +
	"\x10UnregisterWorker\x12#.automation.UnregisterWorkerRequest\x1a$.automation.UnregisterWorkerResponse\x12@\n" +
	"\bPollTask\x12\x1b.automation.PollTaskRequest\x1a\x17.automation.TaskRequest\x12H\n" +
	"\fCompleteTask\x12\x16.automation.TaskResult\x1a .automation.CompleteTaskResponse\x12`\n" +
	"\x11StartLiveWorkflow\x12$.automation.StartLiveWorkflowRequest\x1a%.automation.StartLiveWorkflowResponse\x12Q\n" +
	"\fExecuteTasks\x12\x1f.automation.ExecuteTasksRequest\x1a .automation.ExecuteTasksResponse\x12W\n" +
	"\x0eGetTaskResults\x12!.automation.GetTaskResultsRequest\x1a\".automation.GetTaskResultsResponse\x12]\n" +
	"\x10CompleteWorkflow\x12#.automation.CompleteWorkflowRequest\x1a$.automation.CompleteWorkflowResponse\x12d\n" +
	"\x11SubscribeFailures\x12$.automation.SubscribeFailuresRequest\x1a'.automation.WorkflowFailureNotification0\x01B\x11Z\x0ffurio_sdk/protob\x06proto3"

var (
	file_proto_automation_proto_rawDescOnce sync.Once
	file_proto_automation_proto_rawDescData []byte
)

func file_proto_automation_proto_rawDescGZIP() []byte {
	file_proto_automation_proto_rawDescOnce.Do(func() {
		file_proto_automation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_automation_proto_rawDesc), len(file_proto_automation_proto_rawDesc)))
	})
	return file_proto_automation_proto_rawDescData
}

var file_proto_automation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_automation_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_proto_automation_proto_goTypes = []any{
	(FailureType)(0),                    // 0: automation.FailureType
	(*RegisterWorkerRequest)(nil),       // 1: automation.RegisterWorkerRequest
	(*PollTaskRequest)(nil),             // 2: automation.PollTaskRequest
	(*CompleteTaskResponse)(nil),        // 3: automation.CompleteTaskResponse
	(*RegisterWorkerResponse)(nil),      // 4: automation.RegisterWorkerResponse
	(*UnregisterWorkerRequest)(nil),     // 5: automation.UnregisterWorkerRequest
	(*UnregisterWorkerResponse)(nil),    // 6: automation.UnregisterWorkerResponse
	(*TaskTypeSchema)(nil),              // 7: automation.TaskTypeSchema
	(*RegisterTaskTypeRequest)(nil),     // 8: automation.RegisterTaskTypeRequest
	(*RegisterTaskTypeResponse)(nil),    // 9: automation.RegisterTaskTypeResponse
	(*GetTaskTypeRequest)(nil),          // 10: automation.GetTaskTypeRequest
	(*GetTaskTypeResponse)(nil),         // 11: automation.GetTaskTypeResponse
	(*ListTaskTypesRequest)(nil),        // 12: automation.ListTaskTypesRequest
	(*ListTaskTypesResponse)(nil),       // 13: automation.ListTaskTypesResponse
	(*TaskRequest)(nil),                 // 14: automation.TaskRequest
	(*TaskResult)(nil),                  // 15: automation.TaskResult
	(*TaskSubmit)(nil),                  // 16: automation.TaskSubmit
	(*TaskSubmitResult)(nil),            // 17: automation.TaskSubmitResult
	(*ExecuteTasksRequest)(nil),         // 18: automation.ExecuteTasksRequest
	(*ExecuteTasksResponse)(nil),        // 19: automation.ExecuteTasksResponse
	(*TaskResultQuery)(nil),             // 20: automation.TaskResultQuery
	(*TaskResultItem)(nil),              // 21: automation.TaskResultItem
	(*GetTaskResultsRequest)(nil),       // 22: automation.GetTaskResultsRequest
	(*GetTaskResultsResponse)(nil),      // 23: automation.GetTaskResultsResponse
	(*StartLiveWorkflowRequest)(nil),    // 24: automation.StartLiveWorkflowRequest
	(*StartLiveWorkflowResponse)(nil),   // 25: automation.StartLiveWorkflowResponse
	(*CompleteWorkflowRequest)(nil),     // 26: automation.CompleteWorkflowRequest
	(*CompleteWorkflowResponse)(nil),    // 27: automation.CompleteWorkflowResponse
	(*SubscribeFailuresRequest)(nil),    // 28: automation.SubscribeFailuresRequest
	(*WorkflowFailureNotification)(nil), // 29: automation.WorkflowFailureNotification
	nil,                                 // 30: automation.RegisterWorkerRequest.MetadataEntry
	nil,                                 // 31: automation.TaskRequest.MetadataEntry
}
var file_proto_automation_proto_depIdxs = []int32{
	30, // 0: automation.RegisterWorkerRequest.metadata:type_name -> automation.RegisterWorkerRequest.MetadataEntry
	7,  // 1: automation.RegisterTaskTypeRequest.task_type:type_name -> automation.TaskTypeSchema
	7,  // 2: automation.GetTaskTypeResponse.task_type:type_name -> automation.TaskTypeSchema
	7,  // 3: automation.ListTaskTypesResponse.task_types:type_name -> automation.TaskTypeSchema
	31, // 4: automation.TaskRequest.metadata:type_name -> automation.TaskRequest.MetadataEntry
	16, // 5: automation.ExecuteTasksRequest.tasks:type_name -> automation.TaskSubmit
	17, // 6: automation.ExecuteTasksResponse.results:type_name -> automation.TaskSubmitResult
	20, // 7: automation.GetTaskResultsRequest.tasks:type_name -> automation.TaskResultQuery
	21, // 8: automation.GetTaskResultsResponse.results:type_name -> automation.TaskResultItem
	0,  // 9: automation.WorkflowFailureNotification.failure_type:type_name -> automation.FailureType
	8,  // 10: automation.TaskRegistryService.RegisterTaskType:input_type -> automation.RegisterTaskTypeRequest
	10, // 11: automation.TaskRegistryService.GetTaskType:input_type -> automation.GetTaskTypeRequest
	12, // 12: automation.TaskRegistryService.ListTaskTypes:input_type -> automation.ListTaskTypesRequest
	1,  // 13: automation.WorkerService.RegisterWorker:input_type -> automation.RegisterWorkerRequest
	5,  // 14: automation.WorkerService.UnregisterWorker:input_type -> automation.UnregisterWorkerRequest
	2,  // 15: automation.WorkerService.PollTask:input_type -> automation.PollTaskRequest
	15, // 16: automation.WorkerService.CompleteTask:input_type -> automation.TaskResult
	24, // 17: automation.WorkerService.StartLiveWorkflow:input_type -> automation.StartLiveWorkflowRequest
	18, // 18: automation.WorkerService.ExecuteTasks:input_type -> automation.ExecuteTasksRequest
	22, // 19: automation.WorkerService.GetTaskResults:input_type -> automation.GetTaskResultsRequest
	26, // 20: automation.WorkerService.CompleteWorkflow:input_type -> automation.CompleteWorkflowRequest
	28, // 21: automation.WorkerService.SubscribeFailures:input_type -> automation.SubscribeFailuresRequest
	9,  // 22: automation.TaskRegistryService.RegisterTaskType:output_type -> automation.RegisterTaskTypeResponse
	11, // 23: automation.TaskRegistryService.GetTaskType:output_type -> automation.GetTaskTypeResponse
	13, // 24: automation.TaskRegistryService.ListTaskTypes:output_type -> automation.ListTaskTypesResponse
	4,  // 25: automation.WorkerService.RegisterWorker:output_type -> automation.RegisterWorkerResponse
	6,  // 26: automation.WorkerService.UnregisterWorker:output_type -> automation.UnregisterWorkerResponse
	14, // 27: automation.WorkerService.PollTask:output_type -> automation.TaskRequest
	3,  // 28: automation.WorkerService.CompleteTask:output_type -> automation.CompleteTaskResponse
	25, // 29: automation.WorkerService.StartLiveWorkflow:output_type -> automation.StartLiveWorkflowResponse
	19, // 30: automation.WorkerService.ExecuteTasks:output_type -> automation.ExecuteTasksResponse
	23, // 31: automation.WorkerService.GetTaskResults:output_type -> automation.GetTaskResultsResponse
	27, // 32: automation.WorkerService.CompleteWorkflow:output_type -> automation.CompleteWorkflowResponse
	29, // 33: automation.WorkerService.SubscribeFailures:output_type -> automation.WorkflowFailureNotification
	22, // [22:34] is the sub-list for method output_type
	10, // [10:22] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_automation_proto_init() }
func file_proto_automation_proto_init() {
	if File_proto_automation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_automation_proto_rawDesc), len(file_proto_automation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_automation_proto_goTypes,
		DependencyIndexes: file_proto_automation_proto_depIdxs,
		EnumInfos:         file_proto_automation_proto_enumTypes,
		MessageInfos:      file_proto_automation_proto_msgTypes,
	}.Build()
	File_proto_automation_proto = out.File
	file_proto_automation_proto_goTypes = nil
	file_proto_automation_proto_depIdxs = nil
}
